gpt-5.4-nano:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-5.4-nano"
        body:
            model: "gpt-5.4-nano"
            max_completion_tokens: 4096

claude-haiku:
    import: "./claude-chat.yaml"
    parameters:
        name: "claude-haiku"
        body:
            model: "claude-haiku-4-5-20251001"

gemini-2.5-flash:
    import: "./gemini-chat.yaml"
    parameters:
        name: "gemini-2.5-flash"
        body:
            model: "gemini-2.5-flash"

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512
