gpt-5.4-nano:
    import: "./openai-chat.yaml"
    parameters:
        name: "gpt-5.4-nano"
        body:
            model: "gpt-5.4-nano"
            max_completion_tokens: 4096

text-davinci-003:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-003"
        body:
            model: "text-davinci-003"
            max_tokens: 512

text-davinci-002:
    import: "./openai-text.yaml"
    parameters:
        name: "text-davinci-002"
        body:
            model: "text-davinci-002"
            max_tokens: 512
